import type { Metadata } from "next";
import {Inter, Calistoga} from "next/font/google";



import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const calistoga = Calistoga({
  weight: "400",
  variable: "--font-calistoga",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${calistoga.variable} h-full antialiased`}
    >
       <body
       className="min-h-full flex flex-col
       bg-gray-900 text-white antialiased"
       >
      {children}
       </body>
    </html>
  );
}
